version: '3.3'

services:
  app-server:
    build:
      context: polaris-app-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/polaris?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: dba
      SPRING_DATASOURCE_PASSWORD: 13e10e1997E
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: polaris-app-client
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polaris
      MYSQL_USER: dba
      MYSQL_PASSWORD: 13e10e1997E
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - backend  

volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    